version: '3.7'
services:
  transparency-php:
    build: ./docker/dev/php-fpm
    container_name: transparency-php
    volumes:
      - ./:/var/www/html

  transparency-nginx:
    build: ./docker/dev/nginx
    container_name: transparency-nginx
    depends_on:
      - transparency-php
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf

  transparency-mysql:
    image: mysql:latest
    container_name: transparency-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=transparency
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

